### YamlMime:ManagedReference
items:
- uid: System.StackOverflowException
  id: StackOverflowException
  children:
  - System.StackOverflowException.#ctor
  - System.StackOverflowException.#ctor(System.String)
  - System.StackOverflowException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: StackOverflowException
  nameWithType: StackOverflowException
  fullName: System.StackOverflowException
  type: Class
  summary: "Исключение, которое возникает, когда стек выполнения переполнен, так как она содержит слишком много вложенных вызовов метода. Этот класс не наследуется."
  remarks: "StackOverflowException генерируется при ошибках переполнения стека выполнения, обычно в случае очень глубокой или неограниченной рекурсии.       StackOverflowException использует COR_E_STACKOVERFLOW HRESULT, который имеет значение 0x800703E9. <xref:System.Reflection.Emit.OpCodes.Localloc>Промежуточный язык (IL) выдает StackOverflowException.</xref:System.Reflection.Emit.OpCodes.Localloc> Список начальных значений свойств для объекта StackOverflowException см. в разделе <xref:System.StackOverflowException.%23ctor%2A>конструкторов.</xref:System.StackOverflowException.%23ctor%2A>      ## Описание версии в .NET Framework 1.0 и 1.1, может перехватить объект StackOverflowException (например, для восстановления после неограниченной рекурсии). Начиная с .NET Framework 2.0, не может перехватывать объект StackOverflowException с `try` / `catch` блок и соответствующий процесс завершается по умолчанию. Следовательно следует писать код, чтобы обнаруживать и предотвращать переполнение стека. Например если приложение зависит от рекурсии, используйте счетчик или условие состояния для завершения рекурсивного цикла. В следующем примере используется счетчик, чтобы убедиться, что количество рекурсивных вызовов `Execute` метод превышает максимальную, определяемую MAX_RECURSIVE_CALLS константа.       [!code-vb[System.StackOverflowException.Class#1](~/add/codesnippet/visualbasic/t-system.stackoverflowex_1.vb)][!code-cs[System.StackOverflowException.Class#1](~/add/codesnippet/csharp/t-system.stackoverflowex_1.cs) ]       >  [!NOTE] настроек применение <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute>атрибут метод, который создает исключение StackOverflowException не оказывает влияния.</xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute>   По-прежнему не может обрабатывать исключения из кода пользователя.       Если приложение размещено общеязыковой среды выполнения (CLR), она может указывать, что среда CLR должна выгрузить домен приложения, где происходит исключение переполнения стека и соответствующий процесс продолжит. Дополнительные сведения см. в разделе [интерфейс ICLRPolicyManager](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class StackOverflowException : SystemException
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.StackOverflowException.#ctor
  id: '#ctor'
  parent: System.StackOverflowException
  langs:
  - csharp
  name: StackOverflowException()
  nameWithType: StackOverflowException.StackOverflowException()
  fullName: System.StackOverflowException.StackOverflowException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.StackOverflowException&quot;> </xref> класса, задание <xref:System.Exception.Message*>свойств нового экземпляра системным сообщением, описывающая ошибку, такие как «Запрошенная операция вызывает переполнение стека».</xref:System.Exception.Message*> Это сообщение учитывает текущую культуру системы."
  remarks: "В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.StackOverflowException>.</xref:System.StackOverflowException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Строка локализованного сообщения об. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public StackOverflowException ();
    parameters: []
  overload: System.StackOverflowException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.StackOverflowException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.StackOverflowException
  langs:
  - csharp
  name: StackOverflowException(String)
  nameWithType: StackOverflowException.StackOverflowException(String)
  fullName: System.StackOverflowException.StackOverflowException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.StackOverflowException&quot;> </xref> класса с указанным сообщением об ошибке."
  remarks: "В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.StackOverflowException>.</xref:System.StackOverflowException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Пустая ссылка (`Nothing` в Visual Basic). |   | <xref:System.Exception.Message%2A>| Строка сообщения об ошибке. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public StackOverflowException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Объект <xref:System.String>, описывающая ошибку.</xref:System.String> Содержимое сообщения должно быть понятно пользователю. Код, вызывающий этот конструктор, должен убедиться, что эта строка локализована для текущего языка и региональных параметров системы."
  overload: System.StackOverflowException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.StackOverflowException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.StackOverflowException
  langs:
  - csharp
  name: StackOverflowException(String,Exception)
  nameWithType: StackOverflowException.StackOverflowException(String,Exception)
  fullName: System.StackOverflowException.StackOverflowException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.StackOverflowException&quot;> </xref> класса с указанным сообщением об ошибке и ссылкой на внутреннее исключение, вызвавшее данное исключение."
  remarks: "Исключение, созданное как прямой результат предыдущего исключения, может содержать ссылку на предыдущее исключение в <xref:System.Exception.InnerException%2A>свойство.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>Свойство возвращает то же значение, которое передается конструктору, или пустую ссылку (`Nothing` в Visual Basic) Если <xref:System.Exception.InnerException%2A>свойства не предоставляет конструктору значение внутреннего исключения.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.StackOverflowException>.</xref:System.StackOverflowException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Ссылка на внутреннее исключение. |   | <xref:System.Exception.Message%2A>| Строка сообщения об ошибке. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public StackOverflowException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение об ошибке с объяснением причин исключения."
    - id: innerException
      type: System.Exception
      description: "Исключение, которое стало причиной текущего исключения. Если `innerException` параметр не является указателем null (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> в Visual Basic), текущее исключение сгенерировано в <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> блок, обрабатывающем внутреннее исключение."
  overload: System.StackOverflowException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.StackOverflowException.#ctor
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException()
  nameWithType: StackOverflowException.StackOverflowException()
  fullName: System.StackOverflowException.StackOverflowException()
- uid: System.StackOverflowException.#ctor(System.String)
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException(String)
  nameWithType: StackOverflowException.StackOverflowException(String)
  fullName: System.StackOverflowException.StackOverflowException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.StackOverflowException.#ctor(System.String,System.Exception)
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException(String,Exception)
  nameWithType: StackOverflowException.StackOverflowException(String,Exception)
  fullName: System.StackOverflowException.StackOverflowException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.StackOverflowException.#ctor*
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException
  nameWithType: StackOverflowException.StackOverflowException
